### ISSUE TITLE
Getting Error

### ISSUE THREAD

**Issue by MohammadAli-Kadiwal** [marinaglancy/moodle-format_flexsections#100]
Exception - Call to undefined function format_flexsections\local\hooks\output\format_flexsections_add_back_link_to_cm()
Debug info:
Error code: generalexceptionmessage
Stack trace:
line 43 of /course/format/flexsections/classes/local/hooks/output/before_footer_html_generation.php: Error thrown
line ? of unknownfile: call to format_flexsections\local\hooks\output\before_footer_html_generation::callback()
line 318 of /lib/classes/hook/manager.php: call to call_user_func()
line 988 of /lib/classes/output/core_renderer.php: call to core\hook\manager->dispatch()
line 94 of /admin/search.php: call to core\output\core_renderer->footer()
Exception - Call to undefined function format_flexsections\local\hooks\output\format_flexsections_add_back_link_to_cm()
Debug info:
Error code: generalexceptionmessage
Stack trace:
line 43 of /course/format/flexsections/classes/local/hooks/output/before_footer_html_generation.php: Error thrown
line ? of unknownfile: call to format_flexsections\local\hooks\output\before_footer_html_generation::callback()
line 318 of /lib/classes/hook/manager.php: call to call_user_func()
line 988 of /lib/classes/output/core_renderer.php: call to core\hook\manager->dispatch()
line 2680 of /lib/classes/output/core_renderer.php: call to core\output\core_renderer->footer()
line 178 of /lib/setuplib.php: call to core\output\core_renderer->fatal_error()
line ? of unknownfile: call to default_exception_handler()

**Comment by marinaglancy** [comment]
Thanks for the report, this is fixed in v4.1.3 released today
