### ISSUE TITLE
Moodle 3.5 compatibility

### ISSUE THREAD

**Issue by lars-derichter** [marinaglancy/moodle-format_flexsections#11]
Will there be a version of this plugin that is compatible with moodle 3.5?

**Comment by ifanlo** [comment]
Totally agree. It is a very useful plugin!

**Comment by photuris5** [comment]
I worry that it's been over a year since this plugin has been worked on. Anyone know of someone that could get this plugin ready for 3.5 at least? Moodle 3.6 is just around the corner.

**Comment by sergepaulus** [comment]
And I confirm this version is NOT compatible with Moodle 3.6.1 - please beware!

**Comment by InFerYes** [comment]
@sergepaulus How is it not compatible? Are you getting errors? Can you give more information?

**Comment by photuris5** [comment]
It doesn't nest topic sections inside other topic sections like it is designed to do.  If you are using this on a version of Moodle that will work and update to a newer version of Moodle, the nested topics will all become single topics with no way to nest them again.

**Comment by marinaglancy** [comment]
Hello, the latest version 3.5.0 is compatible with Moodle 3.5-3.8
I have tested the nested sections and they all still work, if you have any more details about the error you are experiencing, please create a new issue. TIA
