### ISSUE TITLE
Merge with parent action lacks confirmation

### ISSUE THREAD

**Issue by raad** [marinaglancy/moodle-format_flexsections#12]
If a user clicks the "Merge with parent" arrow, the merge happens without any confirmation, and it's not easily undone, so it would be really useful to have a confirmation step.

We implemented this feature here at the University of Cambridge, by adding in an additional JavaScript file, an additional language string, and patching the renderer.
I can provide a pull request or the patch and files, whichever is convenient!

**Comment by marinaglancy** [comment]
Thanks for the suggestion! The confirmation is added in plugin version 3.5.0
