### ISSUE TITLE
Hide Icon has disappeared

### ISSUE THREAD

**Issue by mkkenya** [marinaglancy/moodle-format_flexsections#14]
We absolute love this plugin and more and more of our teachers have found a lot of value in it. Thanks for your hard work on this. Since the most recent update we have noticed the following

The hide icon and action for sections and subsections has completely disappeared. It was there in the previous version... in fact if we downgrade the version the hide action comes back.

**Comment by marinaglancy** [comment]
Hello ! The icon is definitely there but it has class="hide" or class="show" which may conflict with your theme that actually hides such elements. Can you please try to use the browser inspector and confirm that the icon is there but just not displayed?

At the same time it was not a good idea to use classes for different action types, I should have used the data- attributes

**Comment by marinaglancy** [comment]
Which theme do you use? Try to switch to Boost theme and check if the icon is displayed

**Comment by mkkenya** [comment]
We are using Boost theme

**Comment by mkkenya** [comment]
but also checked Clean theme as well

**Comment by marinaglancy** [comment]
what version of Moodle? Can you attach screenshot? Did you check inspector? The CSS can come from other plugins too, not just theme

**Comment by mkkenya** [comment]
When looking at the code we can see the action there... but cant click it, and cant see it

**Comment by mkkenya** [comment]
Moodle Version: 3.6
![Cant Hide](https://user-images.githubusercontent.com/22518448/81568643-bcd2b080-93a6-11ea-9a50-2f3cda42ef86.png)

**Comment by marinaglancy** [comment]
did you inspect the code? Do you see what causes the icon to disappear? 
This is my screenshot on vanilla Moodle 3.6 without any additional plugins:
![Screenshot 2020-05-11 at 16 15 18](https://user-images.githubusercontent.com/836986/81571763-ab87a500-93a2-11ea-8128-4046ac04aa4c.png)

**Comment by marinaglancy** [comment]
This is the diff between the latest version and the version before it
https://github.com/marinaglancy/moodle-format_flexsections/compare/3.2.2...3.5.0

Among other changes I removed these styles:
{code}
/* Overwrite bootstrapbase styles */
.format-flexsections .course-content ul.flexsections .controls a.hide,
.format-flexsections .course-content ul.flexsections .controls a.show {display:inline;}
{code}

My reasoning was that bootstrapbase is no longer used and they are not needed (and my testing proved it). I guess, there is still something in your installation that overrides these classes

**Comment by mkkenya** [comment]
Thanks so much for your fast response - below is what I am seeing:
![Hide](https://user-images.githubusercontent.com/22518448/81572904-784a1380-93ac-11ea-9013-40c0e205b799.png)
We have not added or updated anything but the plugin so I suspect something older in our installation like you mention... but I am not seeing what it could be (with my very limited knowledge sorry, I am a bit naïve in this, quite new. Which I know does not help you out much.)

**Comment by mkkenya** [comment]
So we know its there and functioning... just cant see it in course

**Comment by marinaglancy** [comment]
thanks for the report. Clearly some CSS conflict, I'm working on a patch

**Comment by marinaglancy** [comment]
preparing https://github.com/marinaglancy/moodle-format_flexsections/pull/15

**Comment by marinaglancy** [comment]
Fixed in version 3.5.1
