### ISSUE TITLE
Moodle 3.8 collapse/expand option

### ISSUE THREAD

**Issue by tuttyk** [marinaglancy/moodle-format_flexsections#16]
Hi,

I have installed the plugin "collapse/expand option" on Moodle 3.8 but the collapse and expand option only work when the edit mode is active, so, doesn't work for the students. I have the lambda theme installed.

**Editing OFF**
![3](https://user-images.githubusercontent.com/69959796/90733579-09465a00-e2cd-11ea-861a-35aa4a403d8b.PNG)

**Editing ON**
![4](https://user-images.githubusercontent.com/69959796/90733691-31ce5400-e2cd-11ea-8d37-c1a3f154d141.PNG)

If you have any recommendation, please let me know.

Thanks,

Diana G.

**Comment by marinaglancy** [comment]
hi Diana, this is how it is supposed to work. The teacher can control which sections are collapsed and which are expanded. There is another issue - https://github.com/marinaglancy/moodle-format_flexsections/issues/8 - requesting the student feature. Pull requests are welcome

**Comment by tuttyk** [comment]
Hi Marina.

Thanks for your answer !
Best,

Diana
