### ISSUE TITLE
Flexible sections support for upcoming Moodle 4.0

### ISSUE THREAD

**Issue by thomasdumm** [marinaglancy/moodle-format_flexsections#21]
We use flexible sections as our main course format. We plan to update to Moodle 4.0 or 4.1 early next year once they are available. Will you update the plugin, so it works with Moodle 4.0? 

I tried to install the latest version of the flexible section plugin to the latest developer branch of Moodle 4.0. Installing the plugin lead to a white screen when doing the usual "update the database" step. Only after deleting the whole flexible sections plugin folder did Moodle 4.0 recover from white screen status and continued to work again.

**Comment by marinaglancy** [comment]
Hello! There are two versions for Moodle LMS 4.0 now:
4.0.0 - with the same UI as 3.x
4.0.1 - completely re-written to follow UI of Moodle 4.0

**Comment by thomasdumm** [comment]
Hello! Thank you!

Marina Glancy ***@***.***> schrieb am So. 19. Juni 2022 um
17:58:
