### ISSUE TITLE
Invisible Tobics are shown in Moodle Mobile

### ISSUE THREAD

**Issue by sberger** [marinaglancy/moodle-format_flexsections#29]
Hidden sections in a course are not shown to students in the browser. In the Moodle app, however, the title of the section is displayed, with a note that it is hidden.

This different display should be the same in both applications.

It would be even better to have the setting, as in the course format Topics or Weeks, that a hidden section should be displayed completely hidden or hidden with a hint.

**Comment by marinaglancy** [comment]
Hello. There is no support for Moodle mobile. It has been requested in https://github.com/marinaglancy/moodle-format_flexsections/issues/75 . Even though this issue is older, I'm going to close it as a duplicate since the other one has a bigger discussion
