### ISSUE TITLE
Create a MOODLE_31_STABLE branch

### ISSUE THREAD

**Issue by rimas-kudelis** [marinaglancy/moodle-format_flexsections#3]
The [Git for Administrators](https://docs.moodle.org/31/en/Git_for_Administrators) page describes a rather convenient way to maintain Moodle by checking it out of git. It also has information about installing extensions similarly, which is the way I use.
However, for that to really work well, the extensions in question should have a stable branch for checking out (because you probably don't want to end up with a WIP state of the extension). Yours has a few such branches, but doesn't have one for the latest Moodle release, hence this issue.
Please create a `MOODLE_31_STABLE` branch in your repository, and only push changes to that branch upon releasing new Moodle 3.1 compatible versions. Thank you!

**Comment by marinaglancy** [comment]
Hello,
code in master branch works on Moodle 2.8, 2.9, 3.0 and 3.1. I do not see any reason to create separate branches for each major moodle release - it means much more maintenance for me. https://moodle.org/plugins/format_flexsections is the best place to download the source code.

**Comment by rimas-kudelis** [comment]
The problem with master is that if you use it for development (as opposed to pushing just tested releases), there is a chance for me to check it out in a broken state. You don't seem to have a `develop` branch, so I assume master is used for development and is, well, unsafe

**Comment by marinaglancy** [comment]
I keep work in progress in the branches and merge into master when I'm ready to release. When I release I also publish the new version in https://moodle.org/plugins/format_flexsections

**Comment by rimas-kudelis** [comment]
I see, OK then, thanks.
