### ISSUE TITLE
Upgrade to Moodle 4.0.2+ failed

### ISSUE THREAD

**Issue by BrunoMalaval** [marinaglancy/moodle-format_flexsections#30]
Hi,

Upgrade from 3.11.7 to 4.0.2 failed due to format_flexsections

Upgrade in cli mode return nothing, and web only response with http error 500
No access to any page

If I remove the plugin, the upgrade works
If I try to install the plugin in Moodle 4.0.2 , it fails again

I catch this trace in cli mode in a test instance of Moodle, if it can help :+1: 

!!! Exception : Class 'core_courseformat\base' not found !!!

Debug info:
Error code: generalexceptionmessage
Stack trace: * line 40 of /course/format/flexsections/lib.php: Error thrown
* line 865 of /lib/classes/component.php: call to include_once()
* line 7772 of /lib/moodlelib.php: call to core_component::get_plugin_list_with_file()
* line 1060 of /lib/setup.php: call to get_plugins_with_function()
* line 46 of /config.php: call to require_once()
* line 41 of /admin/cli/upgrade.php: call to require()

Thanks a lot 

Bruno

**Comment by marinaglancy** [comment]
Hi Bruno
There has been a number of major changes in API between Moodle versions 3.11 and 4.0. One of the changes is the different name of the base class for course format plugins.

Please make sure that you perform upgrade in the following way:
- put your site in maintenance mode
- change the code of your Moodle to 4.*
- change the code of this plugin to the version for Moodle 4
- purge the caches 
- run upgrade
- take your site out of maintenance mode

From the backlog you posted it looks like either your plugin version doesn't match Moodle version, or you have a cache of the class names

**Comment by marinaglancy** [comment]
Bruno,
Your backlog says that Lin/setup.php calls get_plugins_with_function on line 1060
This is the code of Moodle 3.11

https://github.com/moodle/moodle/blob/MOODLE_311_STABLE/lib/setup.php#L1060

In Moodle 4.0 this line is different. You didn't upgrade your Moodle correctly!

https://github.com/moodle/moodle/blob/MOODLE_400_STABLE/lib/setup.php#L1060

**Comment by BrunoMalaval** [comment]
Hi,

You're right for the update, git doesn't update all the files.
I make a new upgrade, and always have an error, but this time it doesn't  block the upgrade.

Here's the trace

PHP Notice:  Class 'format_base' has been renamed for the autoloader and is now deprecated. Please use 'core_courseformat\base' instead.* line 142 of /lib/classes/component.php: call to debugging()
* line ? of unknownfile: call to core_component::classloader()
* line 38 of /course/format/flexsections/lib.php: call to spl_autoload_call()
* line 865 of /lib/classes/component.php: call to include_once()
* line 7855 of /lib/moodlelib.php: call to core_component::get_plugin_list_with_file()
* line 1084 of /lib/setup.php: call to get_plugins_with_function()
* line 46 of /config.php: call to require_once()
* line 41 of /admin/cli/upgrade.php: call to require()
 in /var/www/moodle-install/lib/weblib.php on line 3257
PHP Fatal error:  Access level to format_flexsections::get_section_number() must be public (as in class core_courseformat\base) in /var/www/moodle-install/course/format/flexsections/lib.php on line 38

Version of format_flexsections plugin is 2022061900

Thanks

**Comment by marinaglancy** [comment]
Hi Bruno
Now it looks like you didn't upgrade the plugin. It has a different version for Moodle 4.0

**Comment by BrunoMalaval** [comment]
Ok thanks,

Upgrade is finished with format flexsections active.
It was long and hard, really don't understand the problem with git

have a nice day

**Comment by marinaglancy** [comment]
Glad you solved it
