### ISSUE TITLE
Topic 0 Custom Section Title Not Respected

### ISSUE THREAD

**Issue by carlicockrell** [marinaglancy/moodle-format_flexsections#36]
When using Topic 0 and selecting "Custom" and creating a title, the title does not appear on the course homepage. (Behavior occurs on Moodle Workplace 3.11+, and was noted in plugin comments in 2021)

**Comment by marinaglancy** [comment]
hello,
the title is hidden on the course page on purpose. I need to remove it from the section editing form so it does not confuse there

**Comment by marinaglancy** [comment]
Hello, new setting was added to 4.0-4.2 version to show the section title and make the general section collapsible. 
Version 3.11 is no longer supported, sorry
