### ISSUE TITLE
Moving sections does not work

### ISSUE THREAD

**Issue by superfoght** [marinaglancy/moodle-format_flexsections#37]
Hi!

We have clients using the format, and it doesn't seem like it's possible to move sections now.

Drag and drop is not working..

And this feature, does not work either:
![image](https://user-images.githubusercontent.com/2778015/199244099-19a475b4-4f7e-4756-a353-88ffe6c3a852.png)

We are using version 4.0.1 (2022061900)

**Comment by marinaglancy** [comment]
hello @superfoght, it is not possible to use drag&drop for sections, I was trying to implement it but it was too confusing with the subsecitons hierarchy, it is not easy to show to the user where the section is going to land

The "Move" button should work. If it does not for you, there may be some JS error. Could you open JS console, try to click the "Move" button and see if there are any errors there.

When I test it I can see the popup like this:

<kbd><img src="https://user-images.githubusercontent.com/836986/200135291-0c8eb170-d843-4e5f-b8f6-39c0e406e9eb.png"></kbd>

**Comment by superfoght** [comment]
Yes, I get the same thing. But When I select a place to move it to, nothing happens. I have recorded a video, also showing the browser console to show that there are no recorded js errors: 
https://www.loom.com/share/3b889340b9124f71b5a8af338ef067c2

**Comment by EgonRasmussen** [comment]
Hi!
Thank you for a really usefull extention. But we have problem with movement of items, as explained by @superfoght. I hope you will make the update for Moodle 4.0. Thank you in advance!

**Comment by marinaglancy** [comment]
Hi Bo, thanks for the video.
I can also reproduce it when trying to move the very last section. Does it happen for you for ANY section move or only when you try to move the last section? I mean, in this example that you showed, are you able to move the second last section to the last position instead?

**Comment by superfoght** [comment]
Hi Marina

Yes, that is correct. If I move other sections to other places than the last section it seems to work. Can you confirm that as well @EgonRasmussen ?

**Comment by EgonRasmussen** [comment]
It is not only the last item, that is a problem. The problem seems to show up when I try to move an item up and across more than 9 items. But the strange thing is that sometimes it works as it should! As if some other factor is influencing it.

**Comment by marinaglancy** [comment]
thanks for these clarifications. It gives me more information to work on this issue

**Comment by kimberley-johnston** [comment]
Hi - we have found a similar issues exists where we attempt to move a section directly below a section that contains a sub-section. In this case the section you're moving gets put at the very bottom of the course. 
So let's say I have the following tree:
- Section A
- Section B
      - Section B1
- Section C

And I try to move Section A directly above Section C I'll end up with the following:
- Section B
      - Section B1
- Section C
- Section A

Hope that helps :)

**Comment by marinaglancy** [comment]
this is indeed very helpful, thank you!
I was able to reproduce it and I created an automated test for it. Ruslan's patch from https://github.com/marinaglancy/moodle-format_flexsections/pull/44 seems to solve it.

**Comment by marinaglancy** [comment]
the patch was merged, I will release a new version soon
