### ISSUE TITLE
line 44 of format.php: call to format_flexsections_renderer->display_section()

### ISSUE THREAD

**Issue by jgupta** [marinaglancy/moodle-format_flexsections#4]
We are getting following error.

Exception - Argument 1 passed to core_course\output\modchooser::__construct() must be an instance of stdClass, instance of course_in_list given, called in [dirroot]/course/renderer.php on line 191

Stack trace:
line 55 of /course/classes/output/modchooser.php: TypeError thrown
line 191 of /course/renderer.php: call to core_course\output\modchooser->__construct()
line 384 of /course/renderer.php: call to core_course_renderer->course_modchooser()
line 175 of /course/format/flexsections/renderer.php: call to core_course_renderer->course_section_add_cm_control()
line 44 of /course/format/flexsections/format.php: call to format_flexsections_renderer->display_section()
line 282 of /course/view.php: call to require()

**Comment by marinaglancy** [comment]
Hello, I can't see how it can be a problem with format_flexsections
It looks like somewhere you call course_get_format($course) passing instance of course_in_list as a $course . I also assume you do it somewhere in custom plugins.
Can you check if you experience the same problem with courses in other course formats?
