### ISSUE TITLE
Activities in subsections are not inheriting parent section restrictions

### ISSUE THREAD

**Issue by renato-araujo** [marinaglancy/moodle-format_flexsections#49]
Hi Marina,

Great course format plugin. Thanks!
When a section has availability conditions to not be shown to some users, its activities are hidden as well.
However, activities inside a subsection are not inheriting its parent section avaliability conditions.

The subsections may not be displayed to users, but its activities show up in the calendar.

In my tests, this problem occurs on Moodle 4.
On Moodle 3.11, it seems to be working properly.

**Comment by pabordel** [comment]
Hi Marina
thanks for developing and maintaining this great course format.
I confirm the bug : restrictions do not apply to subsection, Only visibility does.
I'm using moodle 4.1.1+ with version  4.0.1 2022061900 of this plugin.

Regards

**Comment by renato-araujo** [comment]
Hi Marina,

Is it possible to fix this issue?

The format_flexsections plugin is really great, very useful and this bug is causing some problems to students.
If a restricted activity show up in the calendar to everyone, some students are submitting it, even if the condition is not set to them.

Sorry for following up and thanks again for the great plugin.

Regards,

Renato

**Comment by marinaglancy** [comment]
Hello! Sorry for not replying earlier. This was fixed today in the version 4.1.1

I actually missed this report and found this problem when I was fixing https://github.com/marinaglancy/moodle-format_flexsections/issues/89

**Comment by renato-araujo** [comment]
Thanks a lot, Marina!
You rock!
