### ISSUE TITLE
Not working on Moodle Mobile

### ISSUE THREAD

**Issue by ajinkyagadewar** [marinaglancy/moodle-format_flexsections#5]
Courses are not visible after using this format

**Comment by ajinkyagadewar** [comment]
Course sections are not visible on moodle mobile. What can be the reason?

**Comment by marinaglancy** [comment]
I don't think mobile app supports course formats at all

**Comment by marinaglancy** [comment]
please discuss it on https://tracker.moodle.org/browse/MOBILE-1551
