### ISSUE TITLE
Move Right and Left - restore functionality (MDL-76993)

### ISSUE THREAD

**Issue by kimberley-johnston** [marinaglancy/moodle-format_flexsections#51]
Hi :)

With the move left and right functionality back in Topics (MDL-76990 and MDL-76993) I'm wondering if this is going to be extended to Flexible Sections? 

Cheers.

**Comment by nomisge** [comment]
Hi :)
I have have activities I copied over into a new course, that were created before the removal of move left and right.
Those activities are still indented.

Looking at MDL-72725 I guess that means, that format_flexsections still has the divs and styles in place.

All that might need to be done is to enable it with the function uses_indentation()
(See https://moodle.org/mod/forum/discuss.php?d=434193#p1749931)

Maybe even as toggable settings option?

Thx,

**Comment by marinaglancy** [comment]
hi everybody! Thanks for this ping. I did not realise that this was done in a minor version in core, I was waiting for 4.2 for it. I will look at it shortly

**Comment by marinaglancy** [comment]
this was fixed in https://github.com/marinaglancy/moodle-format_flexsections/pull/53 , I will make a new release soon
