### ISSUE TITLE
Add multiple places to add (sub)sections not only at the bottom

### ISSUE THREAD

**Issue by pjonker** [marinaglancy/moodle-format_flexsections#56]
You can now only add (sub)sections at the bottom of the page. It would be great if you could do that at the bottom of the page.

**Comment by marinaglancy** [comment]
There is a PR attempting to do it - https://github.com/marinaglancy/moodle-format_flexsections/pull/45
but it does not work very well yet, maybe with some extra work it will

**Comment by marinaglancy** [comment]
In the version 4.0.4 that will be released today - 2023-07-02 - I have added the "Add section" link between the sections but only for the first-level sections (also for the first-level subsections for sections that are displayed as a link).

I have tried to add this link for all levels but the UI became very messy and it was hard to see which link belongs to which section.

Let me know if this is a suitable compromise for you.

**Comment by marinaglancy** [comment]
I'm going to close this issue as resolved
