### ISSUE TITLE
Have 2 options to return to the course

### ISSUE THREAD

**Issue by pjonker** [marinaglancy/moodle-format_flexsections#57]
Have 2 options to return to the course (like in Multitabs our current format) return to the section and return to the course (see 2 pics below)
<img width="411" alt="Scherm­afbeelding 2023-05-31 om 10 34 46" src="https://github.com/marinaglancy/moodle-format_flexsections/assets/855826/c4fc45ff-c2c8-4e93-942c-7c5032a23288">
<img width="414" alt="Scherm­afbeelding 2023-05-31 om 10 34 53" src="https://github.com/marinaglancy/moodle-format_flexsections/assets/855826/b8a75a13-c17f-4bb7-847c-9cf507cf1d1b">

**Comment by marinaglancy** [comment]
Hello Peter,
just making sure that I understand you correctly
You have
* a course page
  * section A that is displayed "as a link"
    * section B that is a child of the section A and is also displayed "as a link"

When you are on section B page you can currently see "Return to section A". You also want to add a link "Return to course" above it, is that correct?

Or are you talking about the links on the activities pages?

**Comment by pjonker** [comment]
Hi Marina, I created a video in which I explain what we are looking for. Hope this helps?

https://github.com/marinaglancy/moodle-format_flexsections/assets/855826/91469aaa-2c6f-4916-bb8b-f334a2b4b296

**Comment by marinaglancy** [comment]
Hope I understood you correctly. In version 4.0.4 there is a site-wide setting to add the "Back to..." link to the activities. However it is only added to the view.php page in the modules and only when it has an 'incourse' pagelayout. Since every activity type can have their own pages and way of displaying information, it is better to test it on all activity types that you use.

**Comment by marinaglancy** [comment]
version 4.0.5 also contains a course setting. I'm going to close this issue as resolved. Thanks
