### ISSUE TITLE
Setting to hide activities and resources in navigation menu

### ISSUE THREAD

**Issue by pjonker** [marinaglancy/moodle-format_flexsections#59]
Setting to hide activities and resources in navigation menu

**Comment by marinaglancy** [comment]
Hi Peter, thanks for the report. Can you elaborate on it a little more please?
When you say "navigation menu" are you talking about the course index that is displayed on the left of the page?
Do you want to have a setting to hide it completely or display only sections there?

**Comment by pjonker** [comment]
Hi Marina, with "navigation menu" I indeed mean the "course index" on the left of the page. The setting would give us the opportunity to either show sections and activities, basically what it is right now, or hide activities and thus only show sections.

**Comment by marinaglancy** [comment]
I see what you mean and I actually like it even more how the course index looks with this feature.

In version 4.0.4 (2023-07-02) I have added a site-wide setting for the accordion effect. Let me know if you have a need for the per-course setting as well.

**Comment by marinaglancy** [comment]
version 4.0.5 (2023-08-08) also contains a course setting. I'm going to close this issue as resolved. Thanks
