### ISSUE TITLE
Options to choose open all sections or one at a time

### ISSUE THREAD

**Issue by pjonker** [marinaglancy/moodle-format_flexsections#61]
Option to choose whether sections can all be open at the same time. In our current format there is a setting to determine that only one section at a time can be opened. Resulting in a sort of Accordion experience. When I open a (sub)section the previous one closes.

**Comment by marinaglancy** [comment]
Hi Peter, in v4.0.4 (2023-07-02) I have added a site-wide setting to enable the "accordion" effect. 

Let me know if you have a need for the per-course setting as well.

**Comment by marinaglancy** [comment]
version 4.0.5 (2023-08-08) also contains a course setting. I also fixed scrolling problem and added functionality that when a section in the course index is clicked it gets open in the course page (but only for accordion mode).
I'm going to close this issue as resolved. Thanks
