### ISSUE TITLE
Can't drag activities or resources as long as the target section is empty

### ISSUE THREAD

**Issue by sntmoodle** [marinaglancy/moodle-format_flexsections#62]
Hi

We use Moodle 4.1 with Flexible sections format.
We recently noticed that you can't drag activities or resources to a section, as long as the target section is empty. When the target section is not empty, drag and drop works fine.

Is this by design, is this a bug or is there a setting error on our system?

Thanks
-SNT

**Comment by chiaravicere** [comment]
We experiment the same.

**Comment by marinaglancy** [comment]
Does it work for you in topics format?
I did not actually do anything special for activities drag&drop in flexsections, it uses the same code as the standard plugins

**Comment by sntmoodle** [comment]
Hi Marina

Dropping in an empty section in **topics** format does work.
Dropping in an empty section in **flexible sections** format does not work.

Thanks
-SNT

**Comment by marinaglancy** [comment]
Hello! This should be fixed in the v4.0.4 that was released today. Thanks for the report!

**Comment by sntmoodle** [comment]
Thank you. Works fine now!
-SNT
