### ISSUE TITLE
JS Bug problem in 4.2

### ISSUE THREAD

**Issue by cs7262** [marinaglancy/moodle-format_flexsections#63]
Hi, Marina. the plugin is not working in Moodle 4.2. I use the New Learning theme. I can't collapse or expand the sections. In 4.1 it works fine.
I wrote to New Learning developer and he said: Just checked this plugin and seems there is a js bug and this plugin doesn't work in all themes, please watch the video: https://www.dropbox.com/s/srget1ogybybpom/epsvv.mp4

Awaiting your reply,

Carlos

**Comment by marinaglancy** [comment]
Hello Carlos,
thanks for the report. You are saying "I can't collapse or expand the sections" but in the video you actually collapse and expand individual sections. 
Just confirming, this bug only affects the "Collapse all" link for you, right?

**Comment by marinaglancy** [comment]
Hi @cs7262 , can you please test if this problem is resolved for you in v4.0.4 ?

**Comment by cs7262** [comment]
Hello, thank you very much for solving the problem. Everything is working
fine. thank you very much again.
Test:
4.0.9 Ok
4.1.4 Ok
4.2.1 Ok

Thanks a lot

Carlos

**Comment by marinaglancy** [comment]
Thanks for the testing! Closing the issue
