### ISSUE TITLE
a lot of margin when mobile in the boost theme

### ISSUE THREAD

**Issue by marcoblancas** [marinaglancy/moodle-format_flexsections#7]
Great course format. Thanks for your work. I'm not sure if this is an issue for this project or for boost.

When I use flexsections format in sites with boost theme based I think there is a lot of margin in the mobile devices.

![seleccion838](https://user-images.githubusercontent.com/5545390/31962302-811f3e90-b8fd-11e7-881c-16ea9a27d8fa.png)

**Comment by marinaglancy** [comment]
Thanks for suggestion. Margins are improved in the latest version. Boost could do better with the margins too, the gray left and right margins could be removed but it's an issue for core

**Comment by marcoblancas** [comment]
Thank you Marina. At the moment we have included this custom css for our boost theme.

ul.flexsections {
    padding-left: 0;
}
