### ISSUE TITLE
Feature request - add collapse/expand option

### ISSUE THREAD

**Issue by haietza** [marinaglancy/moodle-format_flexsections#8]
The ability to organize course content in subsections is great! It would be wonderful if this course format also provided the ability to collapse/expand subsections on the main course page (akin to the Bootstrap accordion).

**Comment by anapresa** [comment]
I totally agree with haietza.
It would be perfect.

Thank you.

**Comment by azmatksa** [comment]
@anapresa  @haietza  Is there any updates regarding the issue, its really a useful feature I see its still not exist.

**Comment by argwallace** [comment]
I agree being able to expand and collapse for students is key. One of the reasons I am wanting to use this plugin is that it enables a flexible option for handling many topics/content. Being that the case, a collapsible/expandable option for students would make this plugin much more usable and inline with its purpose.

**Comment by marinaglancy** [comment]
Hello!
Version 4.0.1 for Moodle 4.0 allows to expand/collapse each section in the view mode. I will not be adding this functionality to 3.x
