### ISSUE TITLE
Error After changing the sections either by deleting or adding new

### ISSUE THREAD

**Issue by rudykartson** [marinaglancy/moodle-format_flexsections#85]
Hi, I am using moodle 4.3 with flex section, can you please why i am getting this error in specific course, this error was not there earlier i deleted some sections added new section after this it is coming, now i have recreate this course again, whenever i add new section or delete, because of this error, even course index is not getting loaded, any solution on urgent basis would be a great help :

Failed to load resource: https://<server>.com/lib/ajax/service.php?sesskey=fG8sG04rHS&info=core_courseformat_get_state 
the server responded with a status of 500 ()
first.js:434 EXCEPTION RAISED WHILE INIT COURSE EDITOR
(anonymous) @ first.js:434Understand this error
first.js:434

**Comment by marinaglancy** [comment]
Hello.
I need more information in order to reproduce or fix this problem. You can enable the developer debugging and error reporting and provide backtraces (they could be found in the error log).

**Comment by rudykartson** [comment]
https://screenrec.com/share/QqBIjp5Xy7  check this, it is not loading the index, no other error is shown and even bulk edit is not working with this.

**Comment by marinaglancy** [comment]
Hello @rudykartson , are you using the very recent weekly release of 4.3? 
Very recent changes to core in https://tracker.moodle.org/browse/MDL-81610 messed up this plugin, it was released about 3 weeks ago

If so, it will be fixed in today's release of format_flexsections

**Comment by marinaglancy** [comment]
Release 4.1.0 is now available 

If you are updating the plugin through git, note that it is now in a different branch, MOODLE_401_STABLE

Can you please confirm that this release fixed your problem?

**Comment by rudykartson** [comment]
Yes I am using the recent version of Moodle 4.3

**Comment by LMSRudy** [comment]
Can i update now, hope my existing course setting will not affect

**Comment by rudykartson** [comment]
@marinaglancy  pls advise can i update now, hope it will not affect my current course setting, in plugin overview it is showing the update available, pls advise

**Comment by rudykartson** [comment]
@marinaglancy I updated menu issue is resolved, thanks, however bulk edit is still not working, it gives option to select multiple items but bulk menu at footer doesn't appear, the way it appears in topics format or any other format

**Comment by marinaglancy** [comment]
Thanks for the feedback. 
Note that the bulk edit was not in original issue description and there is a different issue about bulk editing - https://github.com/marinaglancy/moodle-format_flexsections/issues/67

**Comment by rudykartson** [comment]
Thanks
