### ISSUE TITLE
Bulk actions menu doesn't appear on Moodle 4.4

### ISSUE THREAD

**Issue by olberger** [marinaglancy/moodle-format_flexsections#87]
Unless I'm mistake, under Moodle 4.4, the bulk actions popup menu, normally displayed at the bottom of the page, won't appear, when flexible sections format is set.

Probably this has changed recently and isn't yet supported.

Thanks in advance.

**Comment by r1ik** [comment]
Hello @marinaglancy , i'm facing the same bug than @olberger .
I use the 2024052200 plugin version, and 4.4 Moodle version (20240524)

Could you tell us if a next version will correct this bug ?
Best regards

**Comment by marinaglancy** [comment]
Hello, this is already reported in https://github.com/marinaglancy/moodle-format_flexsections/issues/67 - I'll close this issue as a duplicate
