### ISSUE TITLE
Multiple secctions inside a sections error

### ISSUE THREAD

**Issue by brunoabcn** [marinaglancy/moodle-format_flexsections#88]
Hi

I created a hierarchy of sections.

- Carrer
   - Semester
       - Week of study
           - Unit to review
               - activities list

This was made for the entire carrer, from carrer until unit to review was a flexible section, the problem was that when I created the 30 subsection brokes an get me this error:

Invalid value in set_user_preference() call, value is is too long for the value column

File: /lib/moodlelib.php
Line: 1493

Error code: codingerror
* line 1493 of /lib/moodlelib.php: coding_exception thrown
* line 808 of /course/format/classes/base.php: call to set_user_preference()
* line 773 of /course/format/classes/base.php: call to core_courseformat\base->persist_to_user_preference()
* line 854 of /course/format/classes/stateactions.php: call to core_courseformat\base->add_section_preference_ids()
* line 137 of /course/format/classes/external/update_course.php: call to core_courseformat\stateactions->section_content_collapsed()
* line ? of unknownfile: call to core_courseformat\external\update_course::execute()
* line 253 of /lib/external/classes/external_api.php: call to call_user_func_array()
* line 83 of /lib/ajax/service.php: call to core_external\external_api::call_external_function()

Now only appears when I open or close section, but I can't find the issue... I will continue reviewing the code

**Comment by brunoabcn** [comment]
It's frustrating, I tryed to solve it. but error continue on another fresh instalation.

**Comment by SamLatsin** [comment]
I'm trying to fix this too, did you succeed?

**Comment by marinaglancy** [comment]
Hello. Unfortunately it is a bug in core, reported as https://tracker.moodle.org/browse/MDL-78073

**Comment by marinaglancy** [comment]
I added a workaround in v4.1.2 that splits large preferences. I am not sure when/if LMS team is going to address the upstream bug
