### ISSUE TITLE
After updating from 4.3.3 to 4.4.2+, an error message appears when collapsing or expanding sections.

### ISSUE THREAD

**Issue by OposicionesArquitectoMadrid** [marinaglancy/moodle-format_flexsections#90]
When I updated Moodle from version 4.3.3 to 4.4.2+, we started encountering the following error, which we hadn't experienced in the previous version:
![image](https://github.com/user-attachments/assets/49a0dcca-836e-4a6f-a296-dad9f8872114)

```
Error code: codingerror
* line 1496 of /lib/moodlelib.php: coding_exception thrown
* line 808 of /course/format/classes/base.php: call to set_user_preference()
* line 795 of /course/format/classes/base.php: call to core_courseformat\base->persist_to_user_preference()
* line 878 of /course/format/classes/stateactions.php: call to core_courseformat\base->remove_section_preference_ids()
* line 137 of /course/format/classes/external/update_course.php: call to core_courseformat\stateactions->section_content_expanded()
* line ? of unknownfile: call to core_courseformat\external\update_course::execute()
* line 253 of /lib/external/classes/external_api.php: call to call_user_func_array()
* line 83 of /lib/ajax/service.php: call to core_external\external_api::call_external_function()
```
This error appears when I copy an existing course, but it does not occur when I create a new course manually. However, the issue reappears when I create a large number of flex sections in the course.

**Comment by GrupoRolePlaying** [comment]
Hi !!
Same problem here. 

PHP : 8.1, 8.2 & 8.3.
Moodle: 4.4.1+

Any update with this?

**Comment by jcmoodle** [comment]
We are experiencing this as well with a site.
PHP: 8.1.29
Moodle: 4.1.12
Plugin version: 4.0.6 (2023122300)

![Screenshot 2024-10-01 at 10 07 43 AM](https://github.com/user-attachments/assets/aab8d9a7-a7fe-455b-b841-269f2a955afa)

```php
Error code: codingerror
* line 1991 of /lib/moodlelib.php: coding_exception thrown
* line 700 of /course/format/classes/base.php: call to set_user_preference()
* line 665 of /course/format/classes/base.php: call to core_courseformat\base->persist_to_user_preference()
* line 599 of /course/format/classes/stateactions.php: call to core_courseformat\base->add_section_preference_ids()
* line 142 of /course/format/classes/external/update_course.php: call to core_courseformat\stateactions->section_index_collapsed()
* line 262 of /lib/externallib.php: call to core_courseformat\external\update_course::execute()
* line 81 of /lib/ajax/service.php: call to external_api::call_external_function()
``` 

We would like to know if there is an update with this issue as well.
Thanks.

**Comment by marinaglancy** [comment]
Hello. Thanks for the report. Unfortunately this is a core bug reported in https://tracker.moodle.org/browse/MDL-78073

**Comment by marinaglancy** [comment]
I added a workaround in v4.1.2 that splits large preferences. I am not sure when/if LMS team is going to address the upstream bug
