### ISSUE TITLE
Replace the deprecated call to set_section_number for a call to set_sectionnum, and replace the deprecated call to get_section_number for a call to get_sectionnum

### ISSUE THREAD

**Issue by Julian-Tovar** [marinaglancy/moodle-format_flexsections#93]
Good day team, in Moodle 4.4, the set_section_number method has been deprecated. Now set_sectionnum is used instead. You can see the deprecation here: https://github.com/moodle/moodle/blob/MOODLE_404_STABLE/course/format/classes/base.php#L612

In a similar manner, the get_section_number method has been deprecated, and get_sectionnum is it's replacement. This deprecation can be seen here: https://github.com/moodle/moodle/blob/MOODLE_404_STABLE/course/format/classes/base.php#L672

Now, our here plugin format_flexsections only has one call to the set_section_number deprecated method, it resides on format.php:41

``` php
if (!empty($displaysection)) {
    $format->set_section_number($displaysection);
}
```

And we have two calls to the get_section_number deprecated method, one of them on classes/output/courseformat/content/cm/controlmenu.php:57

``` php
$sr = $this->format->get_section_number();
```

And the other one on classes/output/courseformat/content/section/controlmenu.php:55

``` php
$sectionreturn = $format->get_section_number();
```

These deprecations can be fixed via direct replacements, for that reason I attach a patch to fix this issue. Let me know if the patch is enough or if you'd prefer a PR, or if I made a mistake or something to be improved on my patch.
[format_flexsections_issue93.patch](https://github.com/user-attachments/files/17235042/format_flexsections_issue93.patch)

Thank you for your attention.

**Comment by marinaglancy** [comment]
Hello
What version of the plugin are you using? No testing of the latest versions shows any depreciation messages. 

The latest version of the plugin is 4.1.1

**Comment by Julian-Tovar** [comment]
Hi Marina! Thank you for your response.

I just switched up to version 4.1.1 of format_flexsections, and the deprecation still persists.

You can see the issue at https://github.com/marinaglancy/moodle-format_flexsections/blob/MOODLE_401_STABLE/format.php#L41 that branch is on 4.1.1 and on that line you can see the call to the deprecated set_section_number method.

I think there are two possible explanations as to why your testing does not show any deprecation messages: Your tests are running on Moodle 4.1 code, which does not contain these deprecations (these deprecations are new to Moodle 4.4). Or maybe your tests don't run the affected code.

Could you please run the format_flexsections 4.1.1 testsuite on a Moodle 4.4 instance? It should show you the deprecation messages if the affected code is run.

**Comment by marinaglancy** [comment]
Hello @Julian-Tovar 
I test plugin on all versions of Moodle, from 4.1 to 4.5 
The function set_section_number() is defined inside the format_flexsections plugin, it overrides the parent function and does not call the parent function in 4.4

I do not understand what problem are you reporting. Do you see any deprecation messages anywhere? Does something not work as intended?

**Comment by Julian-Tovar** [comment]
Hey Marina, so sorry for wasting your time.

Just now I saw in lib.php the

``` php
public function set_section_number(int $sectionnum): void {
    global $CFG;
    if ((int)$CFG->branch >= 404) {
        parent::set_sectionnum($sectionnum);
    } else {
        parent::set_section_number($sectionnum);
    }
}
```

And the:

``` php
public function get_section_number(): int {
    global $CFG;
    if ((int)$CFG->branch >= 404) {
        return (int)parent::get_sectionnum();
    } else {
        return parent::get_section_number();
    }
}
```

This is factually more than enough and is effectively equivalent to the patch I posted, so this issue is not necessary.

Thanks again.
