### ISSUE TITLE
Error: "Invalid value in set_user_preference() call, value is is too long for the value column" 

### ISSUE THREAD

**Issue by rigwbm** [marinaglancy/moodle-format_flexsections#94]
Hello, I am writing to help me to solve this error: when I create flexible sections in Moodle when I reach a certain number of sections and subsections (I have approx. 5 main sections and 162 subsections) I get the error: “I can't create flexible sections in Moodle”: “codingerror/A coding error detected, must be corrected by a programmer: Invalid value in set_user_preference() call, value is too long for the value column”. 

The error apparently lets create new sections and subsections but the error message persists and reappears every time I exit and return again to the course containing the error, or either press over another section in the same course. 

In the courses where I have few sections and subsections I do not get this error so I assume it is due to the number of sections and subsections. I have tried to configure in the plugin options a higher number of sections and subsections but the error persists. 

I have tried to delete sections and subsections within the course that has the error, but still the message persists and I have no choice but to delete the entire course and start again.

Thank you in advance for your support for this error. 

![Captura de pantalla 2024-10-07 014704](https://github.com/user-attachments/assets/73d8073a-2bf2-4fd9-af1d-03afdce24d95)

**Comment by marinaglancy** [comment]
Hello
This was reported before, see https://github.com/marinaglancy/moodle-format_flexsections/issues/90

It is an issue with Moodle core but there is a workaround added in format_flexsections in version 4.1.2

**Comment by rigwbm** [comment]
Thanks Marina, you do a great job with your apps and collaborations in Moodle ✌️
